// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuS2ZsbLErFBn89WuTYDsF1NDjvalGxtA',
    appId: '1:684690494286:web:712f211be3b40ff9d2841f',
    messagingSenderId: '684690494286',
    projectId: 'proj-express',
    authDomain: 'proj-express.firebaseapp.com',
    storageBucket: 'proj-express.appspot.com',
    measurementId: 'G-98QNJLJB6B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDd_n1Lf1omhzEdovcvWk0NmK0AwJ5tL5Q',
    appId: '1:684690494286:android:11e64383ae7985a6d2841f',
    messagingSenderId: '684690494286',
    projectId: 'proj-express',
    storageBucket: 'proj-express.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAopBm2w9csKrP9Z_yQd99YvX-VDoYa9Es',
    appId: '1:684690494286:ios:f8601af9f42dce78d2841f',
    messagingSenderId: '684690494286',
    projectId: 'proj-express',
    storageBucket: 'proj-express.appspot.com',
    iosBundleId: 'com.karindam.express',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAopBm2w9csKrP9Z_yQd99YvX-VDoYa9Es',
    appId: '1:684690494286:ios:daeda4257aefdb05d2841f',
    messagingSenderId: '684690494286',
    projectId: 'proj-express',
    storageBucket: 'proj-express.appspot.com',
    iosBundleId: 'com.karindam.express.RunnerTests',
  );
}
